### ISSUE TITLE
4K上下文完全不够用啊，能出个16K的吗？

### ISSUE THREAD

**Issue by gaye746560359** [01-ai/Yi-1.5#10]
4K上下文完全不够用啊，能出个16K的吗？

**Comment by Yimi81** [comment]
正在讨论，请保持关注~

**Comment by JoeFee2024** [comment]
希望出个32k的，😄

**Comment by Yimi81** [comment]
现已开源以下模型：
✅ Yi-1.5-34B-Chat-16k
✅ Yi-1.5-34B-Base-32k
✅ Yi-1.5-9B-Chat-16k
✅ Yi-1.5-9B-Base-32k

各大平台均可下载：
✅ 抱抱脸：https://huggingface.co/collections/01-ai/yi-2023-11-663f3f19119ff712e176720f
✅ ModelScope：https://www.modelscope.cn/organization/01ai
✅ WiseModel：https://wisemodel.cn/organization/01.AI

Have fun and enjoy!
