### ISSUE TITLE
对于发展方向，提点小建议

### ISSUE THREAD

**Issue by wencan** [01-ai/Yi-1.5#17]
Yi-1.5的“自我”介绍为：“Compared with Yi, Yi-1.5 delivers stronger performance in coding, math, reasoning, and instruction-following capability, while still maintaining excellent capabilities in language understanding, commonsense reasoning, and reading comprehension.”

在绝大多数场景中，coding、math的能力都是不需要的。gpt之类也已经在这方面做得比较好。
站在我这个应用开发者的角度，更希望有一款指令跟随能力很强，还节能减排的大模型。

**Comment by Yimi81** [comment]
感谢您的建议，已经记录并反馈啦
