### ISSUE TITLE
what is the prompt template on ollama 

### ISSUE THREAD

**Issue by taozhiyuai** [01-ai/Yi-1.5#3]
what is the prompt template on ollama

**Comment by Yimi81** [comment]
see https://ollama.com/library/yi:v1.5/blobs/62fbfd9ed093

**Comment by szj2ys** [comment]
> see https://ollama.com/library/yi:v1.5/blobs/62fbfd9ed093

We need version 34b, hurry up!

**Comment by Yimi81** [comment]
@szj2ys https://ollama.com/library/yi:34b-v1.5  done, thank you to the ollama team~
