### ISSUE TITLE
Fast Tokenizer add unexpected space token

### ISSUE THREAD

**Issue by NIL-zhuang** [01-ai/Yi-1.5#37]
Hi Yi developers, Yi-1.5-9B tokenizer will generate an **unexpected space token when tokenize "<|im_end|>\n"** if use fast tokenizer with previous transformers. While it performs normal with transformers 4.42.4 or without fast tokenizer.

What is the correct way to tokenize "<|im_end|>\n"? 
How is it tokenized in SFT stage?

### Old version transformers w/ tokenizer_fast

* transformers v4.36.5 / v4.41.2
* use_fast=True

```python
>>> tokenizer = AutoTokenizer.from_pretrained("01-ai/Yi-1.5-9B-Chat")
>>> tokenizer("<|im_end|>")
{'input_ids': [7], 'attention_mask': [1]}
>>> tokenizer("<|im_end|>\n")
{'input_ids': [7, 59568, 144], 'attention_mask': [1, 1, 1]}
```
In this case, there is an unexpected token 59568, which refers to space

### New transformers w/ tokenizer_fast

* transformers 4.42.4
* use_fast=True
```python
>>> tokenizer = AutoTokenizer.from_pretrained("01-ai/Yi-1.5-9B-Chat")
>>> tokenizer("<|im_end|>\n")
{'input_ids': [7, 144], 'attention_mask': [1, 1]}
```

### Old transformers w/o tokenizer_fast

* transformers 4.41.2
* use_fast=False

```python
>>> tokenizer = AutoTokenizer.from_pretrained("01-ai/Yi-1.5-9B-Chat", use_fast=False)
>>> tokenizer("<|im_end|>\n")
{'input_ids': [7, 144], 'attention_mask': [1, 1]}
```

**Comment by Haijian06** [comment]
Thanks to @NIL-zhuang for the question, yes, it is currently related to the version of transformers written. There are some new workarounds available (not limited by version) such as
Download tokenizer_config.json and change add_prefix_space=false, then use the following code
```python
import json
from transformers import AutoModelForCausalLM, PreTrainedTokenizerFast

model_path = '01-ai/Yi-1.5-9B-Chat'
config_path = '/content/tokenizer_config.json' # modified to your local path

# Local modified tokenizer_config.json (True --> false)
with open(config_path, 'r', encoding='utf-8') as f.
    tokenizer_config = json.load(f)

tokenizer = PreTrainedTokenizerFast.from_pretrained(model_path, **tokenizer_config)

# test
encoded_text = tokenizer.encode('<|im_start|>assistant\n')
decoded_text = tokenizer.decode(encoded_text)

print(encoded_text)
print(decoded_text)
```

**Comment by NIL-zhuang** [comment]
@Haijian06 Thank you for your kind reply. 
And I wonder which is the correct SFT setting, should I change add_prefix_space=false in SFT stage?

**Comment by Haijian06** [comment]
Thanks for the question, you don't have to change add_prefix_space=false, It is correct to follow the default settings, this problem only arises when the model inference
