### ISSUE TITLE
从transformers推理切换到vllm推理效果变差

### ISSUE THREAD

**Issue by HIT-Owen** [01-ai/Yi-1.5#7]
**模型：**01ai/Yi-1.5-9B-Chat
**代码：**均为官方提供的代码
**生成参数：**transformers和vllm生成参数均设置为temperature=0.3, top_p=0.7
**问题：**鸡柳是鸡身上哪个部位？

**transformers生成结果：**
![image](https://github.com/01-ai/Yi-1.5/assets/30472646/e08f3177-dcb6-4157-9e68-76b2283cd7b4)

**vllm生成结果：**
![image](https://github.com/01-ai/Yi-1.5/assets/30472646/0b357ade-17ef-4e74-afa4-b8a568e3fa4b)

其中vllm试了很多种生成参数，生成了多次，但是没有一次是对的结果。。。

**Comment by LIUKAI0815** [comment]
个人感觉和vllm的chat_template有关，参考https://github.com/QwenLM/Qwen/issues/728    https://github.com/vllm-project/vllm/issues/2051 这两个网页

**Comment by LIUKAI0815** [comment]
https://github.com/QwenLM/Qwen/issues/728

**Comment by LIUKAI0815** [comment]
https://zhuanlan.zhihu.com/p/658780653

**Comment by LIUKAI0815** [comment]
https://github.com/vllm-project/vllm/issues/2947
